// Fitted parameters for the holistic score.
//
// Generated by scripts/calibrate.mjs. Do not hand-tune.
//
// Fitted on 6297 human-scored argumentative essays (PERSUADE 2.0),
// held-out test of 1571. The affine anchor maps that fitted scale onto
// ETS's own using ETS's published scored samples, because PERSUADE is grade
// 6-12 writing on a different rubric and its 1-6 is not ETS's 1-6.

export const VECTOR_MEANS = [
  6.036294,
  21.303319,
  5.890583,
  0.525932,
  98.894248,
  27.402445,
  11.294994,
  0.724382,
  2.117957,
  66.471457,
  0.522042,
  0.081900,
  1.144637,
  0.061190,
  0.904700,
  0.155937,
  0.419342,
  0.936001,
  0.201336,
  0.064475,
  0.238050,
  1.284104,
  0.091986,
  0.205812,
  0.500179,
  0.344450,
  0.063364,
  1.487375,
  0.735985,
  0.763244,
  0.386648,
  0.771569,
  0.607781,
];

export const VECTOR_STD_DEVS = [
  0.454610,
  10.664180,
  3.999317,
  0.289802,
  57.900649,
  36.184535,
  10.523146,
  0.145889,
  1.092770,
  16.334079,
  0.616590,
  0.032137,
  0.933740,
  0.021734,
  0.675029,
  0.240888,
  0.794559,
  2.501237,
  0.290154,
  0.271400,
  0.596981,
  1.609027,
  0.157374,
  0.404294,
  0.275536,
  0.475189,
  0.278873,
  2.012477,
  0.322653,
  0.224693,
  0.324375,
  0.801623,
  0.639427,
];

export const COEFFICIENTS = [
  0.714415,
  0.112396,
  -0.037847,
  0.044098,
  0.046841,
  -0.066059,
  -0.064807,
  0.038614,
  -0.007768,
  0.125639,
  0.027081,
  0.095440,
  -0.062043,
  0.014614,
  0.006086,
  0.007151,
  -0.018203,
  0.004662,
  -0.017162,
  -0.008188,
  0.034097,
  0.022309,
  0.031922,
  0.002052,
  -0.002267,
  -0.045772,
  -0.006503,
  -0.051670,
  0.019970,
  0.034148,
  -0.026420,
  -0.051851,
  -0.040255,
  3.746769,
];

// predicted = slope * blended + intercept
export const ETS_ANCHOR = {
  slope: 1.260338,
  intercept: -0.944245,
};

// Half the width of the reported band, derived from held-out error rather than
// chosen to look confident.
export const BAND_HALF_WIDTH = {
  heuristicOnly: 0.50,
  withAi: 0.50,
};

export const CALIBRATION_META = {
  fittedAt: "2026-07-30",
  trainSize: 6297,
  testSize: 1571,
  testMae: 0.4528,
  testQwk: 0.8134,
  testPearson: 0.8520,
  etsMaxError: 0.709,
  etsSpearman: 0.943,
  etsStrictlyMonotonic: false,
  etsWorstInversion: 0.130,
};
